from setuptools import setup, find_packages

setup(name='feedbackcontent',
      version='0.1.0',
      description='Feedback on Content: Toxic Comments',
      url='',
      license='Proprietary',
      author='Vinaya Mandke',
      author_email='vmandke90@gmail.com',
      packages=find_packages(),
      include_package_data=True,
      install_requires=['pytest==3.0.7',
                        'numpy==1.16.1',
                        'matplotlib==3.0.2',
                        'lxml==4.3.1',
                        'pandas==0.24.1',
                        'seaborn==0.9.0',
                        'PyICU==1.9.8',
                        'polyglot==16.7.4',
                        'scikit-learn==0.20.2',
                        'funcy==1.11',
                        'matplotlib-venn==0.11.5',
                        'PyStemmer==1.3.0',
                        'Flask==0.12',
                        'Faker==1.0.2',
                        'gunicorn==19.6.0',
                        'jupyter==1.0.0'],
      entry_points={})
